[package]
name = "counter"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
borsh = "0.9"
solana-program = "=2.0.3"
thiserror = "1.0"

[lib]
crate-type = ["cdylib", "lib"]
